#!/bin/bash

list="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

echo

for file in $list ; do

	fping -c1 -t300 $device 2>/dev/null 1>/dev/null
       
	if [ "$?" > 2 ] ; then
		echo "$file is alive"; 
	
	else 
		echo "$file is dead"; 
	fi

	echo
done
echo
exit 0


