#!/bin/bash

list="rpi51 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

echo

for file in $list ; do

	Response=$(ping -c 1 $file)
	Second=$(echo $?)
	echo $Response
	echo $?       
	if [[ $Second == *"0"* ]] ; then
		echo "Result: $file is alive";
		 
	
	else 
		echo "$file is dead"; 
	fi

	echo
done
echo
exit 0


